preset: psr12

enabled:
  - align_phpdoc
  - alpha_ordered_imports
  - array_indentation
  - binary_operator_spaces
  - blank_line_before_return
  - cast_spaces
  - clean_namespace
  - const_separation
  - hash_to_slash_comment
  - heredoc_to_nowdoc
  - include
  - integer_literal_case
  - laravel_phpdoc_order
  - laravel_phpdoc_separation
  - linebreak_after_opening_tag
  - method_separation
  - multiline_comment_opening_closing
  - no_alternative_syntax
  - no_binary_string
  - no_blank_lines_after_phpdoc
  - no_blank_lines_after_return
  - no_blank_lines_after_throw
  - no_blank_lines_between_imports
  - no_empty_phpdoc
  - no_empty_statement
  - no_extra_block_blank_lines
  - no_extra_consecutive_blank_lines
  - no_multiline_whitespace_around_double_arrow
  - no_multiline_whitespace_before_semicolons
  - no_short_bool_cast
  - no_singleline_whitespace_before_semicolons
  - no_spaces_inside_offset
  - no_unset_cast
  - no_unused_imports
  - no_unused_lambda_imports
  - no_useless_else
  - no_useless_return
  - no_whitespace_before_comma_in_array
  - normalize_index_brace
  - nullable_type_declarations
  - object_operator_without_whitespace
  - phpdoc_add_missing_param_annotation
  - phpdoc_indent
  - phpdoc_inline_tag_normalizer
  - phpdoc_link_to_see
  - phpdoc_no_access
  - phpdoc_no_package
  - phpdoc_no_useless_inheritdoc
  - phpdoc_return_self_reference
  - phpdoc_scalar
  - phpdoc_single_line_var_spacing
  - phpdoc_trim
  - phpdoc_types
  - phpdoc_types_null_last
  - phpdoc_var_without_name
  - post_increment
  - print_to_echo
  - short_array_syntax
  - short_list_syntax
  - simple_to_complex_string_variable
  - single_quote
  - space_after_semicolon
  - standardize_not_equals
  - switch_continue_to_break
  - trailing_comma_in_multiline_array
  # - trailing_comma_in_multiline_definition - available only for PHP 8.0 and newer
  - trim_array_spaces
  - unalign_equals
  - unary_operator_spaces
  - union_type_without_spaces
  - whitespace_after_comma_in_array
