preset: recommended

enabled:
  - concat_with_spaces
  - const_separation
  - const_visibility_required
  - linebreak_after_opening_tag
  - logical_operators
  - multiline_comment_opening_closing
  - no_blank_lines_after_return
  - no_extra_block_blank_lines
  - no_spaces_after_function_name
  - no_useless_else
  - non_printable_character
  - nullable_type_declarations
  - phpdoc_add_missing_param_annotation
  - phpdoc_link_to_see
  - short_list_syntax
  - simple_to_complex_string_variable
  - strict_comparison

disabled:
  - concat_without_spaces
  - no_unneeded_control_parentheses
  # PHP documentation should not be that strict
  - phpdoc_no_access
  - phpdoc_no_package
  - phpdoc_no_useless_inheritdoc
  - phpdoc_order

finder:
  exclude:
    - examples
