language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm

before_install:
  - composer self-update

install:
  - composer install

before_script:

script:
  - vendor/bin/phpunit
  - vendor/bin/phpcs src --standard=PSR2
  - vendor/bin/phpcs Tests --standard=PSR2


